name: 'labeler-validator'
description: 'Validates that the required labels are present on a pull request.'

inputs:
  github-token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'