name: 'labler-release'
description: 'Handles semantic versioning based on labels applied to pull requests.'

inputs:
  patch-release-script:
    description: 'Script to run for patch release'
    required: true
  minor-release-script:
    description: 'Script to run for minor release'
    required: true
  major-release-script:
    description: 'Script to run for major release'
    required: true
  release-branch-name: 
    description: The release branch name
    required: false
  get-current-version-script:
    description: 'Script to get the current version'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.js'